Repository EZAS-Team/Leaflet-Map-Editor, pull requests merged in 2022-09, with the labels that each got.

#17 Added the ability to add markers to the map using events
  Pages/Editor/html/Editor.html
  Pages/Editor/js/Callbacks.js
  Pages/Editor/js/Editor.js
  Pages/Editor/js/Features/MapFeature.js
  Pages/Editor/js/Features/MarkerFeature.js
Labels: enhancement, help wanted

#23 Elliot property editor working
  Pages/Editor/html/Editor.html
  Pages/Editor/js/Callbacks.js
  Pages/Editor/js/Editor.js
  Pages/Editor/js/EditorRequirements.js
  Pages/Editor/js/Features/MapFeature.js
  Pages/Editor/js/Features/MarkerFeature.js
  Pages/Editor/js/Util/GUID.js
  Pages/Editor/js/Util/StateHandle.js
  Pages/Editor/stylesheet/Editor.css
  Resources/Features/Marker/Icons/default-blue.png
  Resources/Features/Marker/Icons/default-green.png
  Resources/Features/Marker/Icons/default-purple.png
  Resources/Features/Marker/Icons/default-red.png
  Resources/Features/Marker/Icons/default-yellow.png
Labels: enhancement

#26 Alex dev to staging
  Pages/Editor/js/Exporter.js
Labels: enhancement, help wanted

#24 Elliot dev -> Staging Property Editor
  Pages/Editor/html/Editor.html
  Pages/Editor/js/Callbacks.js
  Pages/Editor/js/Editor.js
  Pages/Editor/js/EditorRequirements.js
  Pages/Editor/js/Exporter.js
  Pages/Editor/js/Features/MapFeature.js
  Pages/Editor/js/Features/MarkerFeature.js
  Pages/Editor/js/Util/GUID.js
  Pages/Editor/js/Util/StateHandle.js
  Pages/Editor/stylesheet/Editor.css
  Resources/Features/Marker/Icons/default-blue.png
  Resources/Features/Marker/Icons/default-green.png
  Resources/Features/Marker/Icons/default-purple.png
  Resources/Features/Marker/Icons/default-red.png
  Resources/Features/Marker/Icons/default-yellow.png
Labels: documentation, help wanted

#31 Added the Ablility to delete features from the map
  Pages/Editor/html/Editor.html
  Pages/Editor/js/Editor.js
  Pages/Editor/js/EditorRequirements.js
  Pages/Editor/js/Features/MapFeature.js
  Pages/Editor/js/Features/MarkerFeature.js
  Pages/Editor/js/Util/StateHandle.js
Labels: enhancement
